=== kelvindecosta/undergrad/courses/BITS_F466/lab/01/PurchaseOrder/PurchaseOrder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 (http://www.altova.com) by BITS-PILANI University, Dubai Campus (BITS-PILANI University, Dubai Campus) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PurchaseOrder">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Item" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="Laptop"/>
										<xs:enumeration value="Mobile"/>
										<xs:enumeration value="Printer"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Price" type="xs:float"/>
							<xs:element name="Quantity">
								<xs:simpleType>
									<xs:restriction base="xs:int">
										<xs:minInclusive value="10"/>
										<xs:maxInclusive value="20"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:int"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="ShippingAddress">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Street" type="xs:string"/>
							<xs:element name="City" type="xs:string"/>
							<xs:element name="Pin">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:pattern value="\d{3}-\d{4}"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ref" type="xs:int"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== kelvindecosta/undergrad/courses/BITS_F466/lab/01/PurchaseOrder/PurchaseOrder_v2.xml
<?xml version="1.0" encoding="UTF-8"?>
<PurchaseOrder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Admin/Documents/service-oriented-computing-lab/lab01/PurchaseOrder/PurchaseOrder.xsd">
	<Item>
		<Name>Laptop</Name>
		<Price>2000</Price>
		<Quantity>20</Quantity>
	</Item>
	<Item>
		<Name>Laptop</Name>
		<Price>200</Price>
		<Quantity>10</Quantity>
	</Item>
	<Item>
		<Name>Printer</Name>
		<Price>2000</Price>
		<Quantity>15</Quantity>
	</Item>
	<ShippingAddress>
		<Street>10 main road</Street>
		<City>Dubai</City>
		<Pin>333-4444</Pin>
	</ShippingAddress>
</PurchaseOrder>
